### ISSUE TITLE
Simplify YAML Interface Flow syntax

### ISSUE THREAD

**Issue by SlavaVedernikov** [SlavaVedernikov/C4InterFlow#118]
### Context

At the moment if you wanted to express Interface Flows in YAML, you'd have to do something like the following:

```yaml
Flows:
  - Type: If
    Expression: string.IsNullOrEmpty(userId)
    Flows:
    - Type: Use
      Expression: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.ThrowNotAuthenticated
  - Type: Use
    Expression: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.MapToCustomerBasket
  - Type: Use
    Expression: DotNetEShop.SoftwareSystems.BasketApi.Containers.Data.Components.RedisBasketRepository.Interfaces.UpdateBasketAsync
  - Type: If
    Expression: response is null
    Flows:
    - Type: Use
      Expression: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.ThrowBasketDoesNotExist
  - Type: Use
    Expression: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.MapToCustomerBasketResponse
```
It's a bit long-winded, so I think there is an opportunity for improvement here.

### Requirement

Change [JObjectStructuresResolver](https://github.com/SlavaVedernikov/C4InterFlow/blob/6ed0bd8ce9f8506748c45514c4e45ae7370177a4/C4InterFlow.Automation/Readers/JObjectStructuresResolver.cs#L85) to de-serialise Interface Flow from a more concise YAML representation like the one below:
```yaml
Flow:
  If:
    Expression: string.IsNullOrEmpty(userId)
    Use: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.ThrowNotAuthenticated
  Use: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.MapToCustomerBasket
  Use: DotNetEShop.SoftwareSystems.BasketApi.Containers.Data.Components.RedisBasketRepository.Interfaces.UpdateBasketAsync
  If:
    Expression: response is null
    Use: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.ThrowBasketDoesNotExist
  Use: DotNetEShop.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.MapToCustomerBasketResponse

```

Ensure that current Interface Flows representations still work. So multiple representations would be supported until version 2 of C4InterFlow.
