### ISSUE TITLE
Add Views for drawing custom diagrams and outputting other data

### ISSUE THREAD

**Issue by SlavaVedernikov** [SlavaVedernikov/C4InterFlow#126]
### Context

At the moment `draw-diagrams` command creates a verity of diagrams based on options passed to it e.g. `interfaces`, `business-processes`, `scopes`, `levels-of-details`, `type` etc.

If `scopes`, `levels-of-details`, `type` are not passed, `draw-diagrams` will use `*` option value for all of them and draws diagrams for all possible combinations of these option values.

Even though this results in already very comprehensive set of diagrams, sometimes there may be a need for some very specific diagrams that would be easy to find.

### Requirements

Add `Views` configuration to AaC, which would be used to draw custom diagrams. Custom diagrams would be located in `Views` sub-directory of the diagrams output directory.

Here is how the `Views` configuration may look (TBC):

```yaml
AaCExample:
  Views:
    CustomView1:
      DrawDiagrams:
        Scopes:
        - SoftwareSystem
        - Namespace
        Types:
        - C4
        - C4 Static
        LevelsOfDetails:
        - Context
        - Container
        Interfaces:
        - AaCExample.SoftwareSystems.System1.Containers.*.Interfaces.*
        - AaCExample.SoftwareSystems.System2.Containers.*.Interfaces.*
        BusinessProceses:
        - AaCExample.BusinessProceses.Process1
        Formats:
        - Svg
        OutputDirectory: .\Diagrams
        AaCInputPaths:
        - .\Architecture
        AaCReaderStrategyType: Yaml
    CustomView2:
      QueryUseFlows:
        Interfaces:
        - AaCExample.SoftwareSystems.System3.Containers.*.Interfaces.*
        Recursive: true
        AaCInputPaths:
        - .\Architecture
        AaCReaderStrategyType:
        IncludeSelf: true
      DrawDiagrams:
        Scopes:
        - SoftwareSystem
        - Namespace
        Types:
        - C4
        - C4 Static
        LevelsOfDetails:
        - Context
        - Container
        BusinessProceses:
        - AaCExample.BusinessProceses.Process1
        Formats:
        - Png
        OutputDirectory: .\Diagrams
        AaCInputPaths:
        - .\Architecture
        AaCReaderStrategyType: Yaml
      
```
Each view would contain one or more properties that would correspond to the CLI commands that should be executed to realise the view, which could consist of many output diagrams or some other output e.g. list of interfaces in a file (TBD).

View `CustomView1` above would execute `draw-diagrams` CLI command with the options specified under `DrawDiagrams` node.  

View `CustomView2` would first execute `query-use-flows` CLI command with the options specified under `QueryUseFlows` node. The output of the `query-use-flows`  command would be stored in the command execution `Context`. 
Then it would  execute `draw-diagrams` CLI command with the options specified under `DrawDiagrams` node.  `draw-diagrams`  command would use the data e.g. `Interfaces` stored in the command execution `Context` as its input for `interfaces` option.
