### ISSUE TITLE
Add support for Partial Interface Paths (Aliases) in Use Flows of YAML AaC

### ISSUE THREAD

**Issue by SlavaVedernikov** [SlavaVedernikov/C4InterFlow#25]
### Context
At the moment Use Flows in YAML AaC Interface definitions require full paths (aliases) to other Interfaces e.g.

```yaml
dotnet:
  eShop:
    Architecture:
      SoftwareSystems:
        BasketApi:
          Containers:
            Grpc:
              Components:
                BasketService:
                  Interfaces:
                    UpdateBasket:
                      Label: Update Basket
                      IsPrivate: false
                      Flow:
                        Flows:
                        - Type: If
                          Expression: string.IsNullOrEmpty(userId)
                          Flows:
                          - Type: Use
                            Expression: dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.ThrowNotAuthenticated
                        - Type: Use
                          Expression: dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.MapToCustomerBasket
                        - Type: Use
                          Expression: dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Data.Components.RedisBasketRepository.Interfaces.UpdateBasketAsync
                        - Type: If
                          Expression: response is null
                          Flows:
                          - Type: Use
                            Expression: dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.ThrowBasketDoesNotExist
                        - Type: Use
                          Expression: dotnet.eShop.Architecture.SoftwareSystems.BasketApi.Containers.Grpc.Components.BasketService.Interfaces.MapToCustomerBasketResponse
```
### Requirement
It would be more convenient and less verbose if it was possible to use partial Interface paths (aliases) when the interface being used in the Flow is in the same Software System, Container or Component. The above example then would look as follows:

```yaml
dotnet:
  eShop:
    Architecture:
      SoftwareSystems:
        BasketApi:
          Containers:
            Grpc:
              Components:
                BasketService:
                  Interfaces:
                    UpdateBasket:
                      Label: Update Basket
                      IsPrivate: false
                      Flow:
                        Flows:
                        - Type: If
                          Expression: string.IsNullOrEmpty(userId)
                          Flows:
                          - Type: Use
                            Expression: Interfaces.ThrowNotAuthenticated
                        - Type: Use
                          Expression: Interfaces.MapToCustomerBasket
                        - Type: Use
                          Expression: Containers.Data.Components.RedisBasketRepository.Interfaces.UpdateBasketAsync
                        - Type: If
                          Expression: response is null
                          Flows:
                          - Type: Use
                            Expression: Interfaces.ThrowBasketDoesNotExist
                        - Type: Use
                          Expression: Interfaces.MapToCustomerBasketResponse
```

The Structure Resolver would then infer the full paths (aliases) based on the relative Paths (Aliases) and the position of the current Structure in the node hierarchy.
