### ISSUE TITLE
Simplify Flows representation in YAML and JSON

### ISSUE THREAD

**Issue by SlavaVedernikov** [SlavaVedernikov/C4InterFlow#70]
### Context
At the moment the only way to represent `Flows` in YAML and JSON is to have an overarching `Flow` object:

```yaml
ToDoAppExample:
  SoftwareSystems:
    ToDoApp:
      Containers:
        Database:
          Interfaces:
            SelectTasks: {}
            InsertTask: {}
        WebApi:
          Interfaces:
            GetTasks:
              Flow:
                Flows:
                  - Type: Use
                    Expression: Database.Interfaces.SelectTasks
            AddTask:
              Flow:
                Flows:
                  - Type: If
                    Expression: Task does not exist
                    Flows:
                    - Type: Use
                      Expression: Database.Interfaces.InsertTask
```

### Requirements
Simplify YAML and JSON representation of `Flows` so that there would be no need for an overarching `Flow` object:

```yaml
ToDoAppExample:
  SoftwareSystems:
    ToDoApp:
      Containers:
        Database:
          Interfaces:
            SelectTasks: {}
            InsertTask: {}
        WebApi:
          Interfaces:
            GetTasks:
              Flows:
                - Type: Use
                  Expression: Database.Interfaces.SelectTasks
            AddTask:
              Flows:
                - Type: If
                  Expression: Task does not exist
                  Flows:
                  - Type: Use
                    Expression: Database.Interfaces.InsertTask
```
