### ISSUE TITLE
Add Namespaces to the Diagrams files system path

### ISSUE THREAD

**Issue by SlavaVedernikov** [SlavaVedernikov/C4InterFlow#87]
### Context

At the moment all **Software Systems** and **Business Processes** auto-generated diagrams are saved in `SoftwareSystems` and `BusinessProcesses` sub-directories of the output directory provided in `--output-dir` option for the `draw-diagrams` CLI command.

This means that if you have two **Software Systems** or **Business Processes** in different **Namespaces**, the diagrams will be potentially overwritten.

### Requirements

Add **Namespaces** sub-directories to the output directory when generating diagrams.

For example, if we had  the following YAML AaC

```
ECommercePlatform:
  BackEnd
    SoftwareSystems:
      BasketService:
  FrontEnd
    SoftwareSystems:
      StorefrontApp:
```
Then the directory structure under the output directory would be as follow:
```
E - Commerce Platform
- Back End
   - Software Systems
      - Basket Service
- Front End
   - Software Systems
      - Storefront App
```
